# Generated by Django 4.2.7 on 2025-04-10 15:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TTSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('tld', models.CharField(max_length=10)),
                ('slow', models.BooleanField(default=False)),
                ('pre_process', models.BooleanField(default=True)),
                ('advanced_tokenize', models.BooleanField(default=False)),
                ('file_path', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
